### ISSUE TITLE
HelloWorld exception: Could not load type 'Microsoft.AspNetCore.Authorization.IAuthorizeData'

### ISSUE THREAD

**Issue by ScottHutchinson** [fsbolero/website#2]
Trying to run the HelloWorld solution for the first time, and I got this run-time error:

https://gist.github.com/ScottHutchinson/a5d9f3646dac2d2dde250d3a30ace80d

VS Code, dotnet CLI on Windows 10:
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by BentTranberg** [comment]
I think you reported the issue in the wrong repo. This issue is also reported here: https://github.com/fsbolero/Bolero/issues/59

I guess the solution is to downgrade to Preview-5.

https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by ScottHutchinson** [comment]
I thought it might be a documentation issue. I will just downgrade for now.
