### ISSUE TITLE
-p abbreviation for --project in dotnet run is deprecated

### ISSUE THREAD

**Issue by stefanalfbo** [fsbolero/website#60]
When following the __Getting started__ tutorial there are some instructions for starting the server part:
```bash
dotnet run -p src/HelloWorld.Server
```
however a warning is displayed when running that command, ```The abbreviation of -p for --project is deprecated. Please use --project.```

More information from [Microsoft](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1174n). I'm happy to create a PR for this if needed.

**Comment by Tarmil** [comment]
Indeed, `--project` is now preferred. Please go ahead and create a PR, thanks!
