### ISSUE TITLE
Documentation pages 404.

### ISSUE THREAD

**Issue by ZeroBomb** [fsbolero/website#62]
Commit 2debee058c3b7539190852e54910680e2a1e1812 appears to have broken all documentation links.  Github now reports 404 for all https://fsbolero.io/docs/ links.

**Comment by Tarmil** [comment]
Ah, looks like the issue is with [this change](https://github.com/fsbolero/Bolero/commit/3dcfac5f1dc614d00dd291bd2c80daa052a40492) done in Bolero just earlier, which breaks the script that builds the reference documentation. I'll fix it right away.

**Comment by Tarmil** [comment]
Done, thanks for the report!
